language: python
python:
- '3.6'
sudo: enabled
addons:
  apt:
    packages:
    - liblapack-dev
    - libopenmpi-dev
    - openmpi-bin
    - libhdf5-serial-dev
    - gfortran
install:
- source continuous_integration/install.sh
- pip install matplotlib
- pip install LFPy
- pip install .
- pip install pytest
script: pytest
deploy:
  provider: pypi
  user: alejoe91
  on:
    branch: master
    tags: true
  password:
    secure: gyk+uOnN1P0lIPRYj3V3UCSLt2GOCnOzpUh4/4MwWdX8SLbGE8Zv1oLpabZ9lWUhjJf6rPDXtYlMIcKY8Civ0l03W44JaaRuhCixDdWwKItOND5aEhZ6LX1fhVKmgN8saV11GVXRclaPhrBp7nNUHMzY4zFZS5tULkMjC3fcpxKPsSjWxtbLNMJ9eg/XhPXDY3TeYv8VPhDwuYPQe8WbseC2YOg99lwBKG8N33mEqkIFXy8LH4BsLHOWXRbVHs64XD5zXU/E7jT73o6ozR6/M1/ZIJN8N6VCwwvK2XJ+s3UyJSw/P5QW5WrGE8pr/VxlKcdMk4E1951CgwU44arCI5mYZ4ORe2Cnm4MGZX/ieECkrCZMeF/74YyDTrB7tVm+M+YPmW+7yTG8wN+I32/xXGUnJG3sNLpeMkSn2ONx83Q/MOxu1l+isIZIJzvZsqOS/GihzO24QIiscAYlV562H6JD3mCK+2EJPZpT4u2dC8aMzPmZ9AGOqHYd8iCRXh9rCxeV8dpeAnxn/r8n9xTY3npHqSFrrYXbIyBTEtdPjnLQaHeYRMuOEVYgKOLExgob+YDJJQV1hBiTzVPzb39v00AcT9ggmNCkyK7ETqU41oxLMWPmdNfvMPeSbrjdSeBdsp3gB1YXT4YRt1WBoMKolzEet0Yqf4iWV0UdQl/M4n0=
